logging:
  file: logs/crudrest.log
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

server:
  servlet:
    context-path: /crudrest

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: @project.name@

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create